### ISSUE TITLE
Fast searching for any cell by content

### ISSUE THREAD

**Issue by polovik** [f35f22fan/Ods2#2]
Is it possible to get cell's position by its contents?
I have an ods which acts as template for a report. It contains cells with MAGIC identifiers. It needs to replace this MAGIC identifiers with actual data.
Iterate over all cells isn't efficiently - because rows and columns count may be variant.

**Comment by f35f22fan** [comment]
I agree it's inefficient but I don't see how it could've been otherwise.
If you know the row you can search for the cell only in that row, if not you'll have the search the whole sheet.

**Comment by polovik** [comment]
I see.
In case of searching over whole sheet: count of rows and columns returned by methods Sheet::CountRows() and Sheet::CountColumns() are really misled:
CountColumns 16384
CountRows 1048576
Actually, the template contains 12 columns and 53 rows.
I've unzip .ods file and found this lines:
<table:table-row table:number-rows-repeated="1048523" table:style-name="ro2">
  <table:table-cell table:number-columns-repeated="16384" /> 
</table:table-row>
So, seems like these methods are based on table:number-XXXXX-repeated fields, but not on actual stored data.

**Comment by f35f22fan** [comment]
number-rows-repeated="1048523" means the implementation must create 1048523 twin rows. Same for columns. It's just a shorthand to save space in the generated XML document (which is then zipped and renamed to .ods instead of .zip).

**Comment by f35f22fan** [comment]
You could add a new public method to the Sheet class, say get_rows_vector() method that would return "QVector<ods::Row*> rows_" from Sheet.hpp and search/iterate over it, it should only contain the 53 "rows" you talked about.
